name: Build Kernel

on:
  workflow_dispatch:

jobs:
  build-kernel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup environment
        run: |
          echo "KERNEL_SOURCE=$(cat config.env | grep -w "KERNEL_SOURCE" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
          echo "KERNEL_BRANCH=$(cat config.env | grep -w "KERNEL_BRANCH" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
          echo "KERNEL_DEFCONFIG=$(cat config.env | grep -w "KERNEL_DEFCONFIG" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
          echo "ENVIRONMENT_VARIABLES=$(cat config.env | grep -w "ENVIRONMENT_VARIABLES" | head -n 1 | cut -d ":" -f 2)" >> $GITHUB_ENV
          echo "ANYKERNEL_SOURCE=$(cat config.env | grep -w "ANYKERNEL_SOURCE" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
          echo "ANYKERNEL_BRANCH=$(cat config.env | grep -w "ANYKERNEL_BRANCH" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV

      - name: Set swap to 10G
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10

      - name: Download toolchain
        run: |
          mkdir aarch64-linux-android-4.9 && curl https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/+archive/refs/tags/android-10.0.0_r47.tar.gz -RLO && tar -C aarch64-linux-android-4.9/ -xf android-10.0.0_r47.tar.gz
          mkdir arm-linux-androideabi-4.9 && curl https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/+archive/refs/tags/android-10.0.0_r47.tar.gz -RLO && tar -C arm-linux-androideabi-4.9/ -xf android-10.0.0_r47.tar.gz
          mkdir clang && curl https://github.com/kdrag0n/proton-clang-build/releases/download/20191109/proton_clang-10.0.0-20191109.tar.zst -RLO && tar -C clang/ --strip-components=1 -xf proton_clang-*.tar.zst

      - name: Clone kernel source
        run: |
          git clone --depth=1 ${{ env.KERNEL_SOURCE }} -b ${{ env.KERNEL_BRANCH }} kernel

      - name: Setup KernelSU
        run: |
          cd $GITHUB_WORKSPACE/kernel
          curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s v0.9.5
          KSU_VERSION=$(cd KernelSU && expr $(/usr/bin/git rev-list --count HEAD) + 10200)
          echo "UPLOADNAME=-KernelSU_$KSU_VERSION" >> $GITHUB_ENV

      - name: Build kernel
        run: |
          export KBUILD_BUILD_HOST=Github-Action
          export KBUILD_BUILD_USER=$(echo ${{ github.actor }} | tr A-Z a-z)
          export LD_LIBRARY_PATH=$GITHUB_WORKSPACE/clang/lib:$LD_LIBRARY_PATH
          export PATH=$GITHUB_WORKSPACE/clang/bin:$GITHUB_WORKSPACE/aarch64-linux-android-4.9/bin:$GITHUB_WORKSPACE/arm-linux-androideabi-4.9/bin:$PATH
          export ARCH=arm64
          export SUBARCH=arm64
          export CLANG_TRIPLE=aarch64-linux-gnu-
          export CROSS_COMPILE=$GITHUB_WORKSPACE/aarch64-linux-android-4.9/bin/aarch64-linux-android-
          export CROSS_COMPILE_ARM32=$GITHUB_WORKSPACE/arm-linux-androideabi-4.9/bin/arm-linux-androideabi-
          cd kernel
          rm -rf out
          mkdir -p out
          make O=out clean
          make O=out mrproper
          make O=out ${{ env.KERNEL_DEFCONFIG }}
          make O=out -j$(nproc --all) ${{ env.ENVIRONMENT_VARIABLES }}

      - name: Package Anykernel3
        run: |
          git clone --depth=1 ${{ env.ANYKERNEL_SOURCE }} -b ${{ env.ANYKERNEL_BRANCH }} AnyKernel3 && rm -rf AnyKernel3/.git AnyKernel3/.github AnyKernel3/README.md
          if [[ -f kernel/out/arch/arm64/boot/Image.gz-dtb ]]; then
            cp kernel/out/arch/arm64/boot/Image.gz-dtb AnyKernel3/Image.gz-dtb
          elif [[ -f kernel/out/arch/arm64/boot/Image-dtb ]]; then
            cp kernel/out/arch/arm64/boot/Image-dtb AnyKernel3/Image-dtb
          elif [[ -f kernel/out/arch/arm64/boot/Image.gz ]]; then
            cp kernel/out/arch/arm64/boot/Image.gz AnyKernel3/Image.gz
          elif [[ -f kernel/out/arch/arm64/boot/Image ]]; then
            cp kernel/out/arch/arm64/boot/Image AnyKernel3/Image
          fi
          if [ -f kernel/out/arch/arm64/boot/dtbo.img ]; then
            cp kernel/out/arch/arm64/boot/dtbo.img AnyKernel3/dtbo.img
          fi
          echo "BUILD_DATE=$(date +%d-%m-%y)" >> $GITHUB_ENV

      - name: Upload kernel to artifact
        uses: actions/upload-artifact@v4
        with:
          name: Kernel-${{ github.run_number }}x${{ env.BUILD_DATE }}
          path: AnyKernel3/*
